### ISSUE TITLE
Summary statistics for national and vsk is not available

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#413]
Once we processed the national or vsk data in the cQube.Summary statistics table is not displaying.
For ex :
![Screenshot from 2022-10-07 08-24-58](https://user-images.githubusercontent.com/57621682/194458250-dccf0ab1-67bb-4eaa-b7ea-881f4138f954.png)

**Comment by chetandg123** [comment]
Retested the defect still it is not showing summary statistics of NVSK or VSK file processed records as table formats

**Comment by murali003** [comment]
VSK data is updated in the log_summary table. @Sharathnaik38 please look into it.

**Comment by htvenkatesh** [comment]
@chetandg123 this is kind of new thing to be implemented for VSK, lets have it open for now. Will discuss and take a call on this.

**Comment by chetandg123** [comment]
@htvenkatesh sure, murali was saying that database has information about summary statistics of VSK files but UI side enhancement is required

**Comment by htvenkatesh** [comment]
@dhanush-2397 can u update the estimated time if it is not able to complete by eod?

**Comment by dhanush-2397** [comment]
@htvenkatesh I have updated the estimated time.
Estimated Time: 17-10-2022  EOD
Work pending:
1) 29 API 's has to be integrated in Front end side
Work Completed:
1) Backend API development completed for all the API's.

**Comment by krishnakr6** [comment]
Pull Request [#451](https://github.com/Sunbird-cQube/cQube_Edu/pull/451)

**Comment by dhanush-2397** [comment]
@htvenkatesh  Task completed and ready for QA

**Comment by htvenkatesh** [comment]
Ok @dhanush-2397 . Thanks

**Comment by devu1454** [comment]
1.In s3 installation -> summary statistics for vsk_diksha_etb_coverage-status.zip and vsk_diksha_etb_qr-coverage.zip is not available. 
2. Table alignment is not proper
3. @padmanabha1234 processed records are not showing.

**Comment by Inchara98** [comment]
@padmanabha1234  output files are not generating in onpremise after processing vsk files

**Comment by devu1454** [comment]
@htvenkatesh Please note

**Comment by htvenkatesh** [comment]
@dhanush-2397 Can u look into this?

**Comment by padmanabha1234** [comment]
Issue is resolved
@TanushreeSG please take a re-test

**Comment by TanushreeSG** [comment]
Yesterday as I was testing data processing issues, I was not able to pull the latest code and redeploy.
Today i will be retesting this bug.

**Comment by TanushreeSG** [comment]
Retested not fixed 
Diksha ETB coverage
Diksha ETB program started 
Diksha ETB QR coverage

![Image](https://user-images.githubusercontent.com/114054046/196614686-b16c0033-9146-4f6a-a567-1a9486856e65.png)

**Comment by dhanush-2397** [comment]
@padmanabha1234 Is Diksha ETB QR coverage json file added?
I'm able to see the above mentioned files when I run the admin console app in my local.

**Comment by padmanabha1234** [comment]
@dhanush-2397 I processed log_summary_diksha_etb_etb-coverage.json, log_summary_diksha_etb_qr-coverage.json. Please check in the gj output bucket

**Comment by htvenkatesh** [comment]
@padmanabha1234 @devu1454 was telling the file names includes vsk keyword... but in the files u shared its not included. @devu1454 can u confirm on this

**Comment by dhanush-2397** [comment]
@devu1454 @htvenkatesh In output bucket "cqube-gj-output" the filenames does not include vsk keyword.
So the data is visible for etb_qr_coverage and etb-coverage .
Please verify once.

**Comment by htvenkatesh** [comment]
@devu1454 @padmanabha1234 please confirm the exact file names which are being used.

**Comment by dhanush-2397** [comment]
@devu1454  @htvenkatesh Please verify once the code is merged I have used 
1) log_summary_vsk_diksha_etb_qr-coverage.json
2) log_summary/log_summary_vsk_diksha_etb_coverage-status.json
and have hidden few reports in the summary statistics which we had discussed in the meeting.

**Comment by htvenkatesh** [comment]
@TanushreeSG @devu1454 can u guys retest and check this?

**Comment by htvenkatesh** [comment]
@devu1454 wts the processed file name?

**Comment by dhanush-2397** [comment]
@devu1454 @padmanabha1234 Is this the file name "log_summary_diksha_learning_sessions.json" used for diksha Learning session summary?

**Comment by devu1454** [comment]
Diksha Learning Sessions Summary still not displaying.


![Image](https://user-images.githubusercontent.com/57621682/197162592-9fe37b75-6209-45c4-a4a0-6bf582f515cd.png)

**Comment by devu1454** [comment]
Working as expected

**Comment by devu1454** [comment]
tested the diksha_etb_etb-coverage.json summary statistics is displaying

**Comment by devu1454** [comment]
tested the log_summary_diksha_etb_qr-coverage.json, Summary statistics is not dispalying

**Comment by devu1454** [comment]
tested the log_summary_diksha_etb_qr-coverage.json working as expected
