### ISSUE TITLE
Azur - Admin console - Download azur files not showing

### ISSUE THREAD

**Issue by chetandg123** [Sunbird-cQube/community#628]
Navigate to admin console -> 
**Issue1:** Download local files card should be changed to Download Azur Files 
**Issue2:** Inside the download local files screen -> Check dropdown having /tmp options instead of 
i.e azure-input, azure-output , azure-emission

![Image](https://user-images.githubusercontent.com/64146636/196458949-53387f76-626e-4872-a5a0-81fa24ef709a.png)

**Comment by dhanush-2397** [comment]
@htvenkatesh @chetandg123 I had a call with sharath
For issue 2 : 
For azure the functionalities are not yet developed.

Issue 1: We can change the name based on storage type

**Comment by htvenkatesh** [comment]
@dhanush-2397 @Sharathnaik38 wts the effort required for the azure code changes?

**Comment by dhanush-2397** [comment]
@htvenkatesh @chetandg123 
1) Issue 1 is fixed.
2) Issue 2 is fixed( Download functionality is pending)

**Comment by htvenkatesh** [comment]
@chetandg123 pls test these completed things for azure support

**Comment by chetandg123** [comment]
@htvenkatesh @dhanush-2397 retested the defect please find the below result 
**Issue1:** is resolved 
**issue2:** : is not fixed if we select cqube-state-input and cqube-state-emission also screen showing list of cqube-state-output files

**Comment by htvenkatesh** [comment]
@chetandg123 for download they are working on, please test for reading and visualising the reports

**Comment by chetandg123** [comment]
@htvenkatesh sure

**Comment by dhanush-2397** [comment]
@htvenkatesh @chetandg123 Issue 2 is fixed and download functionality also working.

**Comment by chetandg123** [comment]
@htvenkatesh @dhanush-2397 Re-tested completed download azur files screen it is working as expected , closing this ticket

**Comment by RNarmatha** [comment]
Issue is fixed
